version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.2
    container_name: aed-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - aed-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aed-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/aed_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=aed_db
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=3600
      - GUNICORN_WORKERS=4
      - GUNICORN_TIMEOUT=120
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    # We'll use the ENTRYPOINT in Dockerfile instead of specifying command here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "/app/api_health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - aed-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: aed-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8181:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aed-network

  redis:
    image: redis:alpine
    container_name: aed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - aed-network

networks:
  aed-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
